# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
GET http://127.0.0.1:8000/api/crawl/note?url=http://xhslink.com/a/WLK1tK7Aorw0
Accept: application/json